version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-demo
    restart: unless-stopped
    volumes:
      - ./src:/var/www
      - ./src/.env:/var/www/.env
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: payment-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
